// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ComposerController from "./composer_controller"
application.register("composer", ComposerController)

import MessageController from "./message_controller"
application.register("message", MessageController)

import ScrollController from "./scroll_controller"
application.register("scroll", ScrollController)
